version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - backend
